window.exportStatements_fta1 = new Map([]);

window.requiredModules_fta1 = ["strong_induction","idx","prod","map"];

window.proof_fta1 = [
 [
  "Quote",
  [
   "val implies Idx"
  ],
  15,
  "An(Am(((m)!=(0))=>(Ax(('val['Nth['prime;n],m,x])=>((x)=('Idx[m,n]))))))"
 ],
 [
  "Quote",
  [
   "val of Idx"
  ],
  16,
  "An(Am(((m)!=(0))=>('val['Nth['prime;n],m,'Idx[m,n]])))"
 ],
 [
  "Quote",
  [
   "prime valuation additive"
  ],
  17,
  "Ap(Am1(Am2(Aa1(Aa2(('prime[p])=>(('val[p,m1,a1])=>(('val[p,m2,a2])=>('val[p,(m1)*(m2),(a1)+(a2)]))))))))"
 ],
 [
  "Quote",
  [
   "Idx additive"
  ],
  18,
  "Am1(Am2(Ai(((m1)!=(0))=>(((m2)!=(0))=>(('Idx[(m1)*(m2),i])=(('Idx[m1,i])+('Idx[m2,i])))))))"
 ],
 [
  "Quote",
  [
   "Idx of prime"
  ],
  19,
  "An(('Idx['Nth['prime;n],n])=(S(0)))"
 ],
 [
  "Quote",
  [
   "Idx of different prime"
  ],
  20,
  "An(Am(((n)!=(m))=>(('Idx['Nth['prime;n],m])=(0))))"
 ],
 [
  "Quote",
  [
   "'Nth prime injective"
  ],
  21,
  "Am(An(((m)!=(n))=>(('Nth['prime;n])!=('Nth['prime;m]))))"
 ],
 [
  "Quote",
  [
   "Idx of prime power"
  ],
  22,
  "An(Ax(('Idx['Pow['Nth['prime;n],x],n])=(x)))"
 ],
 [
  "Quote",
  [
   "Idx of cross prime power"
  ],
  23,
  "Am(An(((m)!=(n))=>(Ax(('Idx['Pow['Nth['prime;n],x],m])=(0)))))"
 ],
 [
  "Quote",
  [
   "Idx additive 2"
  ],
  24,
  "Am1(Am2(Ai((((m1)*(m2))!=(0))=>(('Idx[(m1)*(m2),i])=(('Idx[m1,i])+('Idx[m2,i]))))))"
 ],
 [
  "Quote",
  [
   "Idx of primes"
  ],
  25,
  "An(Am(('Idx['Nth['prime;n],m])=('Where['eq[m,n];S(0),0])))"
 ],
 [
  "Quote",
  [
   "Idx injective"
  ],
  26,
  "Ax(Ay(((x)!=(0))=>(((y)!=(0))=>((Ai(('Idx[x,i])=('Idx[y,i])))=>((x)=(y))))))"
 ],
 [
  "Quote",
  [
   "Prod 0 case"
  ],
  27,
  "Ax(('Prod[;x,0])=(S(0)))"
 ],
 [
  "Quote",
  [
   "Prod nonzero case"
  ],
  28,
  "Ax(An(('Prod[;x,S(n)])=(('Prod[;x,n])*('Idx[x,n]))))"
 ],
 [
  "Quote",
  [
   "strong_induction"
  ],
  29,
  "(Ax((Ay(((y)<(x))=>(P[y])))=>(P[x])))=>(Ax(P[x]))"
 ],
 [
  "AddRelation",
  [
   5,
   "'ftamap",
   "('Pow['Nth['prime;@3],'Idx[@1,@3]])=(@5)",
   0
  ],
  -1,
  ""
 ],
 [
  "S",
  [
   29,
   "P",
   "((S(0))<=(@))=>(('Prod['Map['ftamap[@];S(0),@],@])=(@))"
  ],
  30,
  "(Ax((Ay(((y)<(x))=>(((S(0))<=(y))=>(('Prod['Map['ftamap[y];S(0),y],y])=(y)))))=>(((S(0))<=(x))=>(('Prod['Map['ftamap[x];S(0),x],x])=(x)))))=>(Ax(((S(0))<=(x))=>(('Prod['Map['ftamap[x];S(0),x],x])=(x))))"
 ],
 [
  "Quote",
  [
   "prime factor reduction"
  ],
  31,
  "Ax(((S(0))<(x))=>(Ep(Ey((((p)*(y))=(x))&&(('prime[p])&&(((y)<(x))&&((y)!=(0))))))))"
 ],
 [
  "Assume",
  [
   "Ay(((y)<(x))=>(((S(0))<=(y))=>(('Prod['Map['ftamap[y];S(0),y],y])=(y))))"
  ],
  32,
  "Ay(((y)<(x))=>(((S(0))<=(y))=>(('Prod['Map['ftamap[y];S(0),y],y])=(y))))"
 ],
 [
  "Assume",
  [
   "(S(0))<=(x)"
  ],
  33,
  "(S(0))<=(x)"
 ],
 [
  "Quote",
  [
   "Map nonzero"
  ],
  34,
  "Ax(An(((x)!=(0))=>(('Map[P;x,n])!=(0))))"
 ],
 [
  "Quote",
  [
   "Map unchanged past n"
  ],
  35,
  "Ax(An(Am(((x)!=(0))=>(((n)<=(m))=>(('Idx['Map[P;x,n],m])=('Idx[x,m]))))))"
 ],
 [
  "Quote",
  [
   "Map applied Eval"
  ],
  36,
  "Ax(Am(An(((x)!=(0))=>(((m)<(n))=>(('Idx['Map[P;x,n],m])=('Eval[P['Idx[x,m],m,x];]))))))"
 ],
 [
  "Quote",
  [
   "Map applied"
  ],
  37,
  "Ax(Am(An(((x)!=(0))=>(((m)<(n))=>(('const3[P;])=>(P['Idx[x,m],m,x,'Idx['Map[P;x,n],m]]))))))"
 ],
 [
  "Quote",
  [
   "Map 0 is unchanged"
  ],
  38,
  "Ax(('Map[P;x,0])=(x))"
 ],
 [
  "SV",
  [
   27,
   "'Map['ftamap[x];S(0),x]"
  ],
  39,
  "('Prod[;'Map['ftamap[x];S(0),x],0])=(S(0))"
 ],
 [
  "Assume",
  [
   "An(((n)<(m))=>(('Idx['Prod['Map['ftamap[x];S(0),x],m],n])=('Idx[x,n])))"
  ],
  40,
  "An(((n)<(m))=>(('Idx['Prod['Map['ftamap[x];S(0),x],m],n])=('Idx[x,n])))"
 ],
 [
  "Assume",
  [
   "(n)<(S(m))"
  ],
  41,
  "(n)<(S(m))"
 ],
 [
  "SV",
  [
   28,
   "'Map['ftamap[x];S(0),x]"
  ],
  42,
  "An(('Prod[;'Map['ftamap[x];S(0),x],S(n)])=(('Prod[;'Map['ftamap[x];S(0),x],n])*('Idx['Map['ftamap[x];S(0),x],n])))"
 ],
 [
  "SV",
  [
   42,
   "m"
  ],
  43,
  "('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))"
 ],
 [
  "SV",
  [
   24,
   "'Prod[;'Map['ftamap[x];S(0),x],m]"
  ],
  44,
  "Am2(Ai(((('Prod[;'Map['ftamap[x];S(0),x],m])*(m2))!=(0))=>(('Idx[('Prod[;'Map['ftamap[x];S(0),x],m])*(m2),i])=(('Idx['Prod[;'Map['ftamap[x];S(0),x],m],i])+('Idx[m2,i])))))"
 ],
 [
  "SV",
  [
   44,
   "'Idx['Map['ftamap[x];S(0),x],m]"
  ],
  45,
  "Ai(((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))!=(0))=>(('Idx[('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]),i])=(('Idx['Prod[;'Map['ftamap[x];S(0),x],m],i])+('Idx['Idx['Map['ftamap[x];S(0),x],m],i]))))"
 ],
 [
  "SV",
  [
   45,
   "n"
  ],
  46,
  "((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))!=(0))=>(('Idx[('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]),n])=(('Idx['Prod[;'Map['ftamap[x];S(0),x],m],n])+('Idx['Idx['Map['ftamap[x];S(0),x],m],n])))"
 ],
 [
  "Assume",
  [
   "(('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=(0)"
  ],
  47,
  "(('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=(0)"
 ],
 [
  "S",
  [
   5,
   "P",
   "P123"
  ],
  48,
  "Ax(Ay(((x)=(y))=>((P123[x])=>(P123[y]))))"
 ],
 [
  "SV",
  [
   48,
   "'Prod[;'Map['ftamap[x];S(0),x],S(m)]"
  ],
  49,
  "Ay((('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(y))=>((P123['Prod[;'Map['ftamap[x];S(0),x],S(m)]])=>(P123[y])))"
 ],
 [
  "DEL",
  [
   48
  ],
  48,
  "Ax(Ay(((x)=(y))=>((P123[x])=>(P123[y]))))"
 ],
 [
  "SV",
  [
   49,
   "('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])"
  ],
  50,
  "(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])))=>((P123['Prod[;'Map['ftamap[x];S(0),x],S(m)]])=>(P123[('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])]))"
 ],
 [
  "DEL",
  [
   49
  ],
  49,
  "Ay((('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(y))=>((P123['Prod[;'Map['ftamap[x];S(0),x],S(m)]])=>(P123[y])))"
 ],
 [
  "S",
  [
   50,
   "P123",
   "(@)=('Prod[;'Map['ftamap[x];S(0),x],S(m)])"
  ],
  51,
  "(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])))=>((('Prod[;'Map['ftamap[x];S(0),x],S(m)])=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))=>((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)])))"
 ],
 [
  "DEL",
  [
   50
  ],
  50,
  "(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])))=>((P123['Prod[;'Map['ftamap[x];S(0),x],S(m)]])=>(P123[('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])]))"
 ],
 [
  "SV",
  [
   4,
   "'Prod[;'Map['ftamap[x];S(0),x],S(m)]"
  ],
  52,
  "('Prod[;'Map['ftamap[x];S(0),x],S(m)])=('Prod[;'Map['ftamap[x];S(0),x],S(m)])"
 ],
 [
  "MP",
  [
   51,
   43
  ],
  53,
  "(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))=>((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))"
 ],
 [
  "MP",
  [
   53,
   52
  ],
  54,
  "(('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)])"
 ],
 [
  "DEL",
  [
   51
  ],
  51,
  "(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])))=>((('Prod[;'Map['ftamap[x];S(0),x],S(m)])=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))=>((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)])))"
 ],
 [
  "DEL",
  [
   52
  ],
  52,
  "('Prod[;'Map['ftamap[x];S(0),x],S(m)])=('Prod[;'Map['ftamap[x];S(0),x],S(m)])"
 ],
 [
  "DEL",
  [
   53
  ],
  53,
  "(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))=>((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))"
 ],
 [
  "S",
  [
   5,
   "P",
   "P123"
  ],
  55,
  "Ax(Ay(((x)=(y))=>((P123[x])=>(P123[y]))))"
 ],
 [
  "SV",
  [
   55,
   "('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])"
  ],
  56,
  "Ay(((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=(y))=>((P123[('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])])=>(P123[y])))"
 ],
 [
  "DEL",
  [
   55
  ],
  55,
  "Ax(Ay(((x)=(y))=>((P123[x])=>(P123[y]))))"
 ],
 [
  "SV",
  [
   56,
   "'Prod[;'Map['ftamap[x];S(0),x],S(m)]"
  ],
  57,
  "((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))=>((P123[('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])])=>(P123['Prod[;'Map['ftamap[x];S(0),x],S(m)]]))"
 ],
 [
  "DEL",
  [
   56
  ],
  56,
  "Ay(((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=(y))=>((P123[('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])])=>(P123[y])))"
 ],
 [
  "S",
  [
   57,
   "P123",
   "(@)=(0)"
  ],
  58,
  "((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))=>(((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=(0))=>(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(0)))"
 ],
 [
  "DEL",
  [
   57
  ],
  57,
  "((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))=>((P123[('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m])])=>(P123['Prod[;'Map['ftamap[x];S(0),x],S(m)]]))"
 ],
 [
  "MP",
  [
   58,
   54
  ],
  59,
  "((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=(0))=>(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(0))"
 ],
 [
  "DEL",
  [
   58
  ],
  58,
  "((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=('Prod[;'Map['ftamap[x];S(0),x],S(m)]))=>(((('Prod[;'Map['ftamap[x];S(0),x],m])*('Idx['Map['ftamap[x];S(0),x],m]))=(0))=>(('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(0)))"
 ],
 [
  "MP",
  [
   59,
   47
  ],
  60,
  "('Prod[;'Map['ftamap[x];S(0),x],S(m)])=(0)"
 ]
];